# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://zjykzk.github.io/"
# Site title
title = "老K随笔"

Paginate = 100

# Copyright
copyright = "(c) 2017 zenk."

# Language
DefaultContentLanguage = "zh"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "simple"

[taxonomies]
    category = "categories"
    tag = "tags"

[author]
    name = "zenk"
    email = "zhangkai.zju@gmail.com"

[params]
    enableGitalk = true
# code releated
    code_syntax_css = "prism.css"
    code_syntax_js = "prism.js"
# zen theme replated configuration
    dateformat = "2006-01-02"
    submitted = true       # Show author and date information for a post.
    poweredby = true       # Show powered by hugo in footer
    logo = false           # Turn off the logo.
    sidebar = false

[params.gitalk]
    clientID = "94870b3efea9c642b0e7" # Your client ID
    clientSecret = "97e434f793caeaa7d09bf5a196cd6c84e6b4debc" # Your client secret
    repo = "zjykzk.github.io" # The repo to store comments
    owner = "zjykzk" # Your GitHub ID
    admin= "zjykzk" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    taskLists = true
    plainIdAnchors = true
    extensions = ["hardLineBreak"]
    extensionmask = []
