# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://zjykzk.github.io/"
title = "老K随笔"
copyright = "(c) 2025 zenk."
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
# Language
DefaultContentLanguage = "zh"

[pagination]
	pagerSize = 100

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/posts/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

[taxonomies]
    category = "categories"
    tag = "tags"

[author]
    name = "zenk"
    email = "zhangkai.zju@gmail.com"

[params]
	# description = "Your meta description"      # Your meta description of the site
  	header_title = "zenk"                 # Your header title
  	header_subtitle = "" # Your header subtitle
  	# home_image = "/images/avatar.png"          # Path to header image starting from the static directory (optional)
  	recent_posts = 7                           # Max amount of recent posts to show
  	mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
	[[params.social]]
    	fa_icon = "fab fa-github fa-1x"
    	href = "http://github.com/zjykzk"
		# 	[[params.social]]
		# fa_icon = "fab fa-linkedin-in fa-1x"
		# href = ""
		# 	[[params.social]]
		# fa_icon = "fab fa-twitter fa-1x"
		# href = ""
		# 	[[params.social]]
		# fa_icon = "fas fa-at fa-1x"
		# href = ""
