# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://zjykzk.github.io/"
# Site title
title = "zenk 随笔"

# Copyright
copyright = "(c) 2017 zenk."

# Language
languageCode = "zh-CN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "zen"

[taxonomies]
    category = "categories"
    tag = "tags"

[author]
    name = "zenk"
    email = "zhangkai.zju@gmail.com"

[params]
# code releated
    code_syntax_css = "prism.css"
    code_syntax_js = "prism.js"
# zen theme replated configuration
    dateformat = "2006-01-02 15:04:05"
    submitted = true       # Show author and date information for a post.
    poweredby = true       # Show powered by hugo in footer
    logo = false           # Turn off the logo.

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    taskLists = true
    plainIdAnchors = true
    extensions = ["hardLineBreak"]
    extensionmask = []
